FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

# usa a porta que a plataforma disponibilizar
ENV PORT=8081

EXPOSE $PORT

CMD exec uvicorn app:app --host 0.0.0.0 --port $PORT
