FROM python:3.12-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

# Não importa a porta, o provedor injeta via $PORT
EXPOSE 8080  

CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port $PORT"]
